# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo content
      uses: actions/checkout@v3
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

  # this Action should follow steps to set up Python build environment
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: "Berlin/requirements.txt"
        
    - name : Build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        path: "Berlin/Dockerfile"
        image: python-build
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
    
        
